server:
  port: 9000

spring:
  profiles:
    include:
      - dev
      - auth

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true

lombok:
  addLombokGeneratedAnnotation: true
