jwt:
  header: Authorization
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  token-validity-in-seconds: 86400
  route:
    authentication:
      path: auth
      refresh: refresh

app:
  oauth2:
    authorized-redirect-uris: http://localhost:3000/oauth2/redirect

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 908397690209-9ebadlr1cbee9rchde46pvs1n9o5a4ic.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
