create table cart (
    id bigint generated by default as identity,
    user_id bigint,
    primary key (id)
);

create table cart_item (
    cart_id bigint not null,
    item_count integer not null,
    item_id bigint,
    cart_item_key bigint not null,
    primary key (cart_id, cart_item_key)
);

create table category (
    id bigint generated by default as identity,
    name varchar(255),
    parent_id bigint,
    primary key (id)
);

create table item (
    id bigint generated by default as identity,
    content varchar(255),
    image_url varchar(255),
    name varchar(255),
    price integer not null,
    review_count integer not null,
    review_rate integer not null,
    stock_quantity integer not null,
    category_id bigint,
    store_id bigint,
    primary key (id)
);

create table order_item (
    id bigint generated by default as identity,
    count integer not null,
    order_price integer not null,
    item_id bigint,
    order_id bigint,
    primary key (id)
);

create table orders (
    id bigint generated by default as identity,
    ordered_at timestamp,
    status varchar(255),
    user_id bigint,
    primary key (id)
);

create table review (
    id bigint generated by default as identity,
    content clob not null,
    grade integer not null,
    item_id bigint,
    user_id bigint,
    primary key (id)
);

create table store (
    id bigint generated by default as identity,
    name varchar(255),
    review_count integer not null,
    review_rate integer not null,
    primary key (id)
);

create table user (
    id bigint generated by default as identity,
    email varchar(255),
    nickname varchar(255),
    password varchar(255),
    provider varchar(255),
    provider_id varchar(255),
    primary key (id)
);

alter table order_item
    add constraint FKt4dc2r9nbvbujrljv3e23iibt
        foreign key (order_id)
            references orders;

alter table cart_item
    add constraint FK1uobyhgl1wvgt1jpccia8xxs3
        foreign key (cart_id)
            references cart;

alter table item
    add constraint FK2n9w8d0dp4bsfra9dcg0046l4
        foreign key (category_id)
            references category;

alter table item
    add constraint FKi0c87m5jy5qxw8orrf2pugs6h
        foreign key (store_id)
            references store;

alter table order_item
    add constraint FKija6hjjiit8dprnmvtvgdp6ru
        foreign key (item_id)
            references item;

alter table orders
    add constraint FKel9kyl84ego2otj2accfd8mr7
        foreign key (user_id)
            references user;

alter table review
    add constraint FK6hb6qqehnsm7mvfgv37m66hd7
        foreign key (item_id)
            references item;

alter table review
    add constraint FKiyf57dy48lyiftdrf7y87rnxi
        foreign key (user_id)
            references user;