name: pr-test

on:
  pull_request:
    branch: develop
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Test and Build
        run: ./gradlew clean build
